{{- if .Values.controller.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "astron.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "astron.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.api.type }}
  selector:
    {{- include "astron.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
  ports:
    - name: api
      port: {{ .Values.service.api.port }}
      targetPort: api
      protocol: TCP
{{- end }}
{{- if .Values.controller.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "astron.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "astron.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.metrics.type }}
  selector:
    {{- include "astron.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
  ports:
    - name: metrics
      port: {{ .Values.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}
