---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gamera.gamera.io
  resources:
  - graphprojections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gamera.gamera.io
  resources:
  - graphprojections/finalizers
  verbs:
  - update
- apiGroups:
  - gamera.gamera.io
  resources:
  - graphprojections/status
  verbs:
  - get
  - patch
  - update
