//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRDSelection) DeepCopyInto(out *CRDSelection) {
	*out = *in
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRDSelection.
func (in *CRDSelection) DeepCopy() *CRDSelection {
	if in == nil {
		return nil
	}
	out := new(CRDSelection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardInclude) DeepCopyInto(out *CardInclude) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardInclude.
func (in *CardInclude) DeepCopy() *CardInclude {
	if in == nil {
		return nil
	}
	out := new(CardInclude)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChatModelConfig) DeepCopyInto(out *ChatModelConfig) {
	*out = *in
	if in.AuthSecretRef != nil {
		in, out := &in.AuthSecretRef, &out.AuthSecretRef
		*out = new(EmbeddingSecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChatModelConfig.
func (in *ChatModelConfig) DeepCopy() *ChatModelConfig {
	if in == nil {
		return nil
	}
	out := new(ChatModelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmbeddingConfig) DeepCopyInto(out *EmbeddingConfig) {
	*out = *in
	if in.AuthSecretRef != nil {
		in, out := &in.AuthSecretRef, &out.AuthSecretRef
		*out = new(EmbeddingSecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmbeddingConfig.
func (in *EmbeddingConfig) DeepCopy() *EmbeddingConfig {
	if in == nil {
		return nil
	}
	out := new(EmbeddingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmbeddingSecretReference) DeepCopyInto(out *EmbeddingSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmbeddingSecretReference.
func (in *EmbeddingSecretReference) DeepCopy() *EmbeddingSecretReference {
	if in == nil {
		return nil
	}
	out := new(EmbeddingSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphProjection) DeepCopyInto(out *GraphProjection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphProjection.
func (in *GraphProjection) DeepCopy() *GraphProjection {
	if in == nil {
		return nil
	}
	out := new(GraphProjection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GraphProjection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphProjectionList) DeepCopyInto(out *GraphProjectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GraphProjection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphProjectionList.
func (in *GraphProjectionList) DeepCopy() *GraphProjectionList {
	if in == nil {
		return nil
	}
	out := new(GraphProjectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GraphProjectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphProjectionSpec) DeepCopyInto(out *GraphProjectionSpec) {
	*out = *in
	out.Neo4j = in.Neo4j
	in.Scope.DeepCopyInto(&out.Scope)
	if in.Relationships != nil {
		in, out := &in.Relationships, &out.Relationships
		*out = make([]RelationshipRule, len(*in))
		copy(*out, *in)
	}
	if in.ResyncInterval != nil {
		in, out := &in.ResyncInterval, &out.ResyncInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.GraphRAG != nil {
		in, out := &in.GraphRAG, &out.GraphRAG
		*out = new(GraphRAGSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphProjectionSpec.
func (in *GraphProjectionSpec) DeepCopy() *GraphProjectionSpec {
	if in == nil {
		return nil
	}
	out := new(GraphProjectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphProjectionStatus) DeepCopyInto(out *GraphProjectionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.LastEmbeddingTime != nil {
		in, out := &in.LastEmbeddingTime, &out.LastEmbeddingTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphProjectionStatus.
func (in *GraphProjectionStatus) DeepCopy() *GraphProjectionStatus {
	if in == nil {
		return nil
	}
	out := new(GraphProjectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphRAGSpec) DeepCopyInto(out *GraphRAGSpec) {
	*out = *in
	in.Embedding.DeepCopyInto(&out.Embedding)
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = new(CardInclude)
		(*in).DeepCopyInto(*out)
	}
	if in.VectorIndex != nil {
		in, out := &in.VectorIndex, &out.VectorIndex
		*out = new(VectorIndexConfig)
		**out = **in
	}
	if in.Chat != nil {
		in, out := &in.Chat, &out.Chat
		*out = new(ChatModelConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphRAGSpec.
func (in *GraphRAGSpec) DeepCopy() *GraphRAGSpec {
	if in == nil {
		return nil
	}
	out := new(GraphRAGSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphView) DeepCopyInto(out *GraphView) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphView.
func (in *GraphView) DeepCopy() *GraphView {
	if in == nil {
		return nil
	}
	out := new(GraphView)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GraphView) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphViewFilters) DeepCopyInto(out *GraphViewFilters) {
	*out = *in
	if in.HiddenKinds != nil {
		in, out := &in.HiddenKinds, &out.HiddenKinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HiddenNamespaces != nil {
		in, out := &in.HiddenNamespaces, &out.HiddenNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LabelFilters != nil {
		in, out := &in.LabelFilters, &out.LabelFilters
		*out = make([]LabelFilter, len(*in))
		copy(*out, *in)
	}
	if in.MaxDistance != nil {
		in, out := &in.MaxDistance, &out.MaxDistance
		*out = new(int32)
		**out = **in
	}
	if in.GroupByNamespace != nil {
		in, out := &in.GroupByNamespace, &out.GroupByNamespace
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphViewFilters.
func (in *GraphViewFilters) DeepCopy() *GraphViewFilters {
	if in == nil {
		return nil
	}
	out := new(GraphViewFilters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphViewList) DeepCopyInto(out *GraphViewList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GraphView, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphViewList.
func (in *GraphViewList) DeepCopy() *GraphViewList {
	if in == nil {
		return nil
	}
	out := new(GraphViewList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GraphViewList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphViewSpec) DeepCopyInto(out *GraphViewSpec) {
	*out = *in
	out.ProjectionRef = in.ProjectionRef
	in.Filters.DeepCopyInto(&out.Filters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphViewSpec.
func (in *GraphViewSpec) DeepCopy() *GraphViewSpec {
	if in == nil {
		return nil
	}
	out := new(GraphViewSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphViewStatus) DeepCopyInto(out *GraphViewStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphViewStatus.
func (in *GraphViewStatus) DeepCopy() *GraphViewStatus {
	if in == nil {
		return nil
	}
	out := new(GraphViewStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelFilter) DeepCopyInto(out *LabelFilter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelFilter.
func (in *LabelFilter) DeepCopy() *LabelFilter {
	if in == nil {
		return nil
	}
	out := new(LabelFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Neo4jConnection) DeepCopyInto(out *Neo4jConnection) {
	*out = *in
	out.AuthSecretRef = in.AuthSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Neo4jConnection.
func (in *Neo4jConnection) DeepCopy() *Neo4jConnection {
	if in == nil {
		return nil
	}
	out := new(Neo4jConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectionReference) DeepCopyInto(out *ProjectionReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectionReference.
func (in *ProjectionReference) DeepCopy() *ProjectionReference {
	if in == nil {
		return nil
	}
	out := new(ProjectionReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectionScope) DeepCopyInto(out *ProjectionScope) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]ResourceSelector, len(*in))
		copy(*out, *in)
	}
	if in.CRDs != nil {
		in, out := &in.CRDs, &out.CRDs
		*out = new(CRDSelection)
		(*in).DeepCopyInto(*out)
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectionScope.
func (in *ProjectionScope) DeepCopy() *ProjectionScope {
	if in == nil {
		return nil
	}
	out := new(ProjectionScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationshipRule) DeepCopyInto(out *RelationshipRule) {
	*out = *in
	out.From = in.From
	out.To = in.To
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationshipRule.
func (in *RelationshipRule) DeepCopy() *RelationshipRule {
	if in == nil {
		return nil
	}
	out := new(RelationshipRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSelector) DeepCopyInto(out *ResourceSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSelector.
func (in *ResourceSelector) DeepCopy() *ResourceSelector {
	if in == nil {
		return nil
	}
	out := new(ResourceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VectorIndexConfig) DeepCopyInto(out *VectorIndexConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VectorIndexConfig.
func (in *VectorIndexConfig) DeepCopy() *VectorIndexConfig {
	if in == nil {
		return nil
	}
	out := new(VectorIndexConfig)
	in.DeepCopyInto(out)
	return out
}
