import { useEffect, useRef, useState } from "react";
import {
  ActionIcon,
  Box,
  Group,
  Loader,
  ScrollArea,
  Stack,
  Text,
  Textarea,
  Tooltip,
} from "@mantine/core";
import { askQuestion, type AnswerCard, type Projection } from "./api";
import { iconForKindOrGeneric } from "./kinds";
import { IconSend2 } from "./icons";

// A single entry in the conversation. Assistant messages carry the resource
// cards that grounded the answer so they can be listed as sources.
interface ChatMessage {
  id: string;
  role: "user" | "assistant" | "error";
  text: string;
  sources?: AnswerCard[];
}

// SourceList renders the resources that grounded an answer as a compact list.
function SourceList({ cards }: { cards: AnswerCard[] }) {
  if (cards.length === 0) return null;
  return (
    <Stack gap={2} mt={6}>
      <Text size="xs" c="dimmed" tt="uppercase" style={{ letterSpacing: "0.05em" }}>
        Sources
      </Text>
      {cards.map((c) => (
        <Group key={c.id} gap={6} wrap="nowrap" align="center">
          <img src={iconForKindOrGeneric(c.kind)} width={12} height={12} alt="" />
          <Text size="xs" c="dimmed" truncate title={`${c.kind} ${c.namespace ? `${c.namespace}/` : ""}${c.name}`}>
            {c.kind} {c.namespace ? `${c.namespace}/` : ""}
            {c.name}
          </Text>
        </Group>
      ))}
    </Stack>
  );
}

function MessageBubble({ message }: { message: ChatMessage }) {
  const isUser = message.role === "user";
  return (
    <Box
      className={
        isUser
          ? "chat-bubble chat-bubble-user"
          : message.role === "error"
            ? "chat-bubble chat-bubble-error"
            : "chat-bubble chat-bubble-assistant"
      }
    >
      <Text size="sm" style={{ whiteSpace: "pre-wrap", wordBreak: "break-word" }}>
        {message.text}
      </Text>
      {message.sources && <SourceList cards={message.sources} />}
    </Box>
  );
}

// ChatPanel is a conversation view over the projection's GraphRAG answer
// endpoint: the user asks natural-language questions about the cluster graph
// and the configured chat provider replies with grounded answers.
export function ChatPanel({ projection }: { projection: Projection }) {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [input, setInput] = useState("");
  const [pending, setPending] = useState(false);
  const viewportRef = useRef<HTMLDivElement>(null);

  // Keep the newest message in view as the conversation grows.
  useEffect(() => {
    viewportRef.current?.scrollTo({
      top: viewportRef.current.scrollHeight,
      behavior: "smooth",
    });
  }, [messages, pending]);

  const send = () => {
    const question = input.trim();
    if (!question || pending) return;
    setInput("");
    setMessages((prev) => [
      ...prev,
      { id: crypto.randomUUID(), role: "user", text: question },
    ]);
    setPending(true);
    askQuestion(projection.namespace, projection.name, question)
      .then((answer) => {
        setMessages((prev) => [
          ...prev,
          {
            id: crypto.randomUUID(),
            role: "assistant",
            text: answer.answer,
            sources: answer.retrieval.cards,
          },
        ]);
      })
      .catch((err: Error) => {
        setMessages((prev) => [
          ...prev,
          { id: crypto.randomUUID(), role: "error", text: err.message },
        ]);
      })
      .finally(() => setPending(false));
  };

  return (
    <div className="chat-panel">
      <ScrollArea className="chat-messages" type="scroll" viewportRef={viewportRef}>
        <Stack gap="sm" p={14}>
          {messages.length === 0 && (
            <Text size="sm" c="dimmed">
              Ask a question about the resources in this projection, e.g. “Which
              pods mount a secret?” Answers are generated by the projection's
              configured chat provider using the cluster graph.
            </Text>
          )}
          {messages.map((m) => (
            <MessageBubble key={m.id} message={m} />
          ))}
          {pending && (
            <Group gap="xs" className="chat-bubble chat-bubble-assistant">
              <Loader size="xs" />
              <Text size="sm" c="dimmed">
                Thinking…
              </Text>
            </Group>
          )}
        </Stack>
      </ScrollArea>
      <div className="chat-input">
        <Textarea
          value={input}
          onChange={(e) => setInput(e.currentTarget.value)}
          onKeyDown={(e) => {
            if (e.key === "Enter" && !e.shiftKey) {
              e.preventDefault();
              send();
            }
          }}
          placeholder="Ask about this projection…"
          autosize
          minRows={1}
          maxRows={5}
          style={{ flex: 1 }}
          disabled={pending}
        />
        <Tooltip label="Send" position="top" withArrow>
          <ActionIcon
            variant="filled"
            size="lg"
            aria-label="Send message"
            onClick={send}
            disabled={pending || input.trim() === ""}
          >
            <IconSend2 size={18} stroke={1.5} />
          </ActionIcon>
        </Tooltip>
      </div>
    </div>
  );
}
